package scr.protool.ejbprointer;
import java.util.*;
import java.sql.Date;
import scr.protool.ejbpro.*;
import javax.ejb.*;
import java.math.BigDecimal;
   

    @Remote
    public interface GenericClient{ 
	public byte[] addProject(byte[] project, byte[] quoteline);
	public byte[] addOnProject(byte[] projects, byte[] quoteline);
	public byte[] projectDetails(int projectId);
	public byte[] projectDetail(int projectId);
	public void updateProject(byte[] project);
	public void updateQuotes(byte[]genericinfo, byte[] quote);
	public byte[] quoteValues(int quoteId);
	public byte[] quotePDFSummary(int quoteid);
	public void deleteProject(byte[] project);
	public byte[] getProjectData();
	public byte[] geneProtoolId();
	public byte[] genePaymentId();
	public byte[] geneAccountsCode(int group);
	public byte[] geneCodeId();
	public byte[] getProjectDetails(int projectId);
	public byte[] geneProjectDate(Date from, Date to);
	public byte[] getProjectDetails(String datefrom, String dateto);
	public byte[] getProjectDetails(String datefrom, String dateto, BigDecimal amtfrom, BigDecimal amtto);
	public byte[] getProjectDetailTitle(String datefrom, String dateto, String tiltle);
	public byte[] getProjectDetailClient(String datefrom, String dateto, String name);
	public byte[] geneProjectAmount(BigDecimal from, BigDecimal to);
	public byte[] getGroupName();
	public byte[] getGroupId();
	public void addAccountsCode(byte[] accountcode);
	public byte[] getAccountsCodeDetails();
	public byte[] getAccountsDetails(int accountsCode);
	public void updateAccountsCode(byte[] editcode);
	public byte[] getHashTableAccountsGroup();
	public byte[] getHashTableAccountCode();
	public byte[] getHashTableAccountCodeAssets();
	public byte[] getPaymentInIds();
	public byte[] getQuoteTotals(int projectId);
	public byte[] getQuoteValues(int projectId);
	public void addPaymentIn(byte[] payment);
	public void updatePaymentIn(byte[] payment);
	public void updateQuote(byte[] newquoteline, byte[] projectId);
	public byte[] getPaymentInfo(int projectid);
	public byte[] getHashTablePaymentInId();
	public byte[] genericAccount(int accountCode);
	public byte[] getHashMapPaymentType();
	public byte[] getPaymentData();
	public byte[] getPaymentData(String datefrom, String dateto);
	public byte[] getPaymentData(String datefrom, String dateto, BigDecimal amtfrom, BigDecimal amtto);
	public byte[] getPaymentData(String datefrom, String dateto, int projectId);
	public byte[] getPaymentData(String datefrom, String dateto, String invoiceNumber);
	public byte[] getIncomingId();
	public void addIncomingIn(byte[] incoming);
	public void updateIncomingIn(byte[] incoming);
	public byte[] getPaymentInDetails(int paymentId);
	public byte[] getPaymentBalance(int paymentId);
	public byte[] getGenericIncoming(int paymentId, int codeId);
	public byte[] getIncomingExclude(int paymentId, int codeId, int incomingId);
	public void addSupplier(byte[] supplierinfo);
	public void addSubContractor(byte[] subContractinfo);
	public byte[] getSupplierData();
	public byte[] getSupplierDataId(String supplierAcc);
	public byte[] getSupplierDataName(String suppliername);
	public byte[] getSupplierDataBalance(BigDecimal from, BigDecimal to);
	public byte[] getSupplierSingleData(int supplierid);
	public byte[] getSupplierSingleDetails(int supplierId);
	public void updateSupplier(byte[] supplier, byte[] supplierId);
	public byte[] projectInfos();
	public byte[] getHashTableProjectCost();
	public void addSupplierInvoice(byte[] supplierinvoice);
	public void addSubContractorInvoice(byte[] subContractorinvoice);
	public void addSubContractorPayment(byte[] subContractorpayment);
	public byte[] getSubContractorSingleDetails(int subcontractorId);
	public byte[] getSubContractorData();
	public byte[] getMaterialOutgoingData();
	public byte[] supplierInvoiceDate(Date from, Date to);
	public byte[] supplierInvoiceAmount(BigDecimal from, BigDecimal to);
	public byte[] supplierInvoiceID(int supplierid);
	public byte[] supplierInvoice(String invoice);
	public byte[] supplierInfoListing();
	public byte[] defaultSupplier();
	public byte[] editSupplierInvoice(int invoiceid);
	public void editSupplierInvoices(byte[] supplierinvoice);
	public byte[] HashTableMaterialPosting();
	public byte[] HashTableAccruedPosting();
	public void addMaterialPayment(byte[] materialpayment);
	public byte[] jornalSize(int id);
	public byte[] getSupplierPaymentDetails(int supplierPaymentId);
	public byte[] materialPaymentBalance(int invoiceId);
	public byte[] supplierBatchInvoice(int supplierId);
	public void addMaterialPayments(byte[] invoiceDetails, byte[] paymentInfo);
	public byte[] getLabourOutgoingData();
	public byte[] getLabourOutgoingData(Date from, Date to);
	public byte[] getLabourOutgoingData(BigDecimal from, BigDecimal to);
	public byte[] getLabourOutgoingData(int subcontrctorId);
	public byte[] getLabourOutgoingData(String invoice);
	public byte[] getSubContractorPaymentDetails(int supplierInvoiceId);
	public byte[] getSubContractorRef(String ref);
	public byte[] getSubContractorData(String subcontractorName);
	public byte[] getSubContractorData(BigDecimal from, BigDecimal to);
	public void updateSubContractor(byte[] subContract, byte[] subContractId);
	public byte[] supplierInfos();
	public byte[] getOperationalExpensesCodes();
	public byte[] getAssetsCodes();
	public byte[] getManualPostingCodes();
	public void addExpensesPaid(byte[] expensePaid);
	public void addExpensesPayable(byte[] expensePayable);
	public void addExpensesPrepaid(byte[] expensePrepaid);
	public byte[] projectUserInfos();
	public void addExpensesAccrued(byte[] accruedPayable);
	public byte[] getSingleUserInfos(int userId);
	public void updatePassword(byte[] users);
	public byte[] getProjectByTitle(String title);
	public byte[] getProjectByName(String name);
	public byte[] prepaidInfomations();
	public byte[] prepaidInfomations(Date from, Date to);
	public byte[] prepaidInfomations(Date from, Date to, BigDecimal amtfrom, BigDecimal amtto);
	public byte[] prepaidInfomations(Date from, Date to, String invoice);
	public byte[] prepaidInfomations(Date from, Date to, int supplier);
	public byte[] allotmentInfoDetails(int prepaidid);
	public byte[] prepaidPaymentBalance(int prepaidId);
	public byte[] expensesResolutions();
	public void addPayableExpensesPayment(byte[] payable);
	public byte[] payableInvoicesSearch();
	public byte[] payableInvoicesSearch(Date from, Date to);
	public byte[] payableInvoicesSearch(Date from, Date to, int supplierId);
	public byte[] payableInvoicesSearch(Date from, Date to, String invoice);
	public byte[] payableInvoicesSearch(Date from, Date to, BigDecimal amtfrom, BigDecimal amtto);
	public byte [] accruedInvoicesSearch();
	public byte [] accruedInvoicesSearch(Date from, Date to, BigDecimal amtfrom, BigDecimal amtto);
	public byte [] accruedInvoicesSearch(Date from, Date to);
	public byte [] accruedInvoicesSearch(Date from, Date to, int supplier);
	public byte [] accruedInvoicesSearch(Date from, Date to, String invoice);
	public byte[] expensesResolutions(String datefrom, String dateto);
	public byte[] expensesResolutions(String datefrom, String dateto, String invoice);
	public byte[] expensesResolutions(String datefrom, String dateto, int supplier);
	public byte[] expensesResolutions(String datefrom, String dateto, BigDecimal amtfrom, BigDecimal amtto);
	public void accruedExpensesPayment(byte[] accruedsettle);
	public byte[] getPayableBalance(int payableId);
	public byte[] getAccruedBalance(int accruedId);
	public byte[] getExpensesPayableDetails(int payableId);
	public byte[] getPayableBalance(Integer payableId);
	public byte[] getAccruedDetails(int accruedId);
	public byte[] paidExpensesResolutionDetails(int id);
	public byte[] payableExpensesResolutionDetails(int id);
	public byte[] prepaidExpensesResolutionDetails(int id);
	public byte[] accruedExpensesResolutionDetails(int id);
	public void addManualPosting(byte[] posting);
	public void editManualPosting(byte[] posted);
	public byte[] manualPostingSearch();
	public byte[] manualPostingSearch(String datefrom, String dateto);
	public byte[] manualPostingSearch(String datefrom, String dateto, String accountsName);
	public byte[] manualPostingSearch(String datefrom, String dateto, int accountsCode);
	public byte[] editableManualPosting(int postedId);
	public byte[] manualPostingDetails(int manual);
	public void addAssets(byte[] details);
	public byte[] getAssetDetails();
	public byte[] getAssetDetails(String datefrom, String dateto);
	public byte[] getAssetDetails(String datefrom, String dateto, int account);
	public byte[] getAssetDetails(String datefrom, String dateto, String description);
	public byte[] getAssetSingleDetails(int assetId);
	public byte[] getEditAssetDetails(int assetId);
	public void editAsset(byte[] assetDetails, byte[] assetId);
	public byte[] getNetBookValue(int assetId);
	public byte[] getProcessedDepreciationDetails(int assetId);
	public void addAssetDisposal(byte[] details);
	public byte[] getHashMapPaymentOutType();
	public byte[] projectFinancialActivities(int projectId);
	public byte[] editableProjectDetails(int projectId);
	public void updateProjectQuote(byte[] project, byte[]genericinfo, byte[] quote);
	
 }